version: '3.7'

services:

    sample:
    container_name: sample
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - '.:/App'
        - '/App/node_modules'
    ports:
        - 8000:8000
    environment:
        - CHOKIDAR_USEPOLLING=true
    
    sample:
        container_name: sample2
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/index'
            - '/index/node_modules'
        ports:
            - 8000:8000
        environment:
            - CHOKIDAR_USEPOLLING=true

    redis:
        image: redis:4
        container_name: cache
        ports:
        - '6379:6379'